### ISSUE TITLE
Running shell commands causes bus error

### ISSUE THREAD

**Issue by seancorfield** [oakes/Paravim#2]
macOS, Zulu JDK 8:

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)

Command: clj -Sdeps "{:deps {paravim {:mvn/version \""RELEASE\""}}}" -J-XstartOnFirstThread -m paravim.start

If I try to run a shell command -- `:!ls` -- it sometimes runs (displaying the output in the original terminal window) but then almost any subsequent vim command crashes the process with SIBGUS. Sometimes it crashes trying to run the command.

(I know it's very early days but it just happened to be the first thing I tried, sorry!)

**Comment by oakes** [comment]
Thanks i'll look into this. I never run shell commands from vim so i'm not surprised it's broken =)

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
