### ISSUE TITLE
no OpenGL context current in the current thread

### ISSUE THREAD

**Issue by paulrd** [oakes/Paravim#4]
I'm getting the following error when I try to run 
```clojure -Sdeps "{:deps {paravim {:mvn/version \""RELEASE\""}}}" -m paravim.start```
on 64-bit Ubuntu 19.04:

``` sh
Execution error (IllegalStateException) at org.lwjgl.opengl.GL/createCapabilities (GL.java:378).
There is no OpenGL context current in the current thread.

Full report at:
/tmp/clojure-16357288125682412018.edn
```
OpenGL version string: 3.1 Mesa 19.0.8

**Comment by oakes** [comment]
Does your system not support a more recent version of opengl? Paravim is trying to use 4.1

**Comment by paulrd** [comment]
Ah thanks for the hint. I need to hunt down the special sauce I need to get my amdgpu to work with opengl 4 instead of 3. To complicate matters, I just updated Ubuntu from 18.10 to 19.04 and this may have overwritten the magical kernel commands that I was using to get this working last time.

**Comment by paulrd** [comment]
Well, I wasn't able to get my driver to use opengl 4.x. My laptop also reports having opengl 3.3 (lenovo thinkpad x220). Opengl support usually can't be upgraded independently of the hardware, so I suppose we might want to file this under 'enhancement' or whatnot to support older opengl versions.

**Comment by oakes** [comment]
Done. I am not even sure that it requires 4.1 honestly. That's what i chose for play-cljc because i think it's the last version that Mac OS supports. It may be possible to lower the requirement.

**Comment by oakes** [comment]
I reduced the required opengl version to 3.3 starting in paravim 0.6.3. Let me know if there are still problems.
