### ISSUE TITLE
If I longpress direction keys, the cursor just moves by 1

### ISSUE THREAD

**Issue by divs1210** [oakes/Paravim#9]
I have to press multiple times to move multiple lines/chars.
I'm on a mac.

**Comment by divs1210** [comment]
Looks like it's related to [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206845385-FYI-for-Lion-users-who-use-IdeaVIM).

**Comment by oakes** [comment]
Yeah it happens on windows too so i don't think it's a mac bug. Might be something about how GLFW handles key events, but i'm not sure why longpress works with letters like hjkl but not arrow keys.

**Comment by oakes** [comment]
I figured it out, i was just ignoring repeat press events. Fixed in 0.14.0. Thanks!
